# Generated by Django 5.1.1 on 2024-10-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='foundation_url',
        ),
        migrations.AddField(
            model_name='donation',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
        migrations.DeleteModel(
            name='DonationTransaction',
        ),
    ]
