# Generated by Django 5.1.1 on 2024-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_donation_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
