# Generated by Django 5.1.1 on 2024-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_remove_donation_images_remove_donation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact_info',
            field=models.CharField(default=874569, max_length=255),
            preserve_default=False,
        ),
    ]
