# Generated by Django 5.1.1 on 2024-11-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_donation_image_alter_donation_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='from_date',
        ),
    ]
