# Generated by Django 5.1.1 on 2024-09-20 17:13

import django.core.validators
import pawssearch.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pawssearchuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawssearchuser',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), pawssearch.accounts.models.name_value_validator], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pawssearchuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3), pawssearch.accounts.models.name_value_validator], verbose_name='Last name'),
        ),
    ]
