# Generated by Django 5.1.1 on 2024-09-16 11:31

import django.db.models.deletion
import pawssearch.posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pet_type', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('OTHER', 'Other')], max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True, validators=[pawssearch.posts.models.image_url_validator])),
                ('region', models.CharField(choices=[('BLAGOEVGRAD', 'Blagoevgrad'), ('BURGAS', 'Burgas'), ('VARNA', 'Varna'), ('VELIKO_TARNOVO', 'Veliko Turnovo'), ('VIDIN', 'Vidin'), ('VRATSA', 'Vratsa'), ('GABROVO', 'Gabrovo'), ('DOBRICH', 'Dobrich'), ('KARDZHALI', 'Kurdzhali'), ('KYUSTENDIL', 'Kyustendil'), ('LOVECH', 'Lovech'), ('MONTANA', 'Montana'), ('PAZARDZHIK', 'Pazardzhik'), ('PERNIK', 'Pernik'), ('PLEVEN', 'Pleven'), ('PLOVDIV', 'Plovdiv'), ('RAZGRAD', 'Razgrad'), ('RUSSE', 'Ruse'), ('SILISTRA', 'Silistra'), ('SLIVEN', 'Sliven'), ('SMOLYAN', 'Smolyan'), ('SOFIA', 'Sofia - city'), ('SOFIA_OBLAST', 'Sofia - region'), ('STARA_ZAGORA', 'Stara Zagora'), ('TARGOVISHTE', 'Turgovishte'), ('HASKOVO', 'Haskovo'), ('SHUMEN', 'Shumen'), ('YAMBOL', 'Yambol')], max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
