# Generated by Django 5.1.1 on 2024-09-28 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('FOUND', 'Found'), ('MISSING', 'Missing'), ('FOR_ADOPTION', 'For Adoption'), ('FOR_SELLING', 'For Selling')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
