# Generated by Django 5.1.1 on 2024-09-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
