# Generated by Django 5.1.1 on 2024-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
